language: node_js
node_js:
- '8'
install:
- yarn install
script:
- yarn run build
notifications:
  email:
    recipients:
    - shangyunliang@xiaomi.com
    on_success: never
    on_failure: always
before_install:
- rm -rf ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_316decf98675_key -iv $encrypted_316decf98675_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.167.23\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- cat ~/.ssh/config
after_success:
- tar -cvjpf dist.tar.bz2 ./dist
- scp dist.tar.bz2 root@123.207.167.23:/var/www
addons:
  ssh_known_hosts: 123.207.167.23
