language: node_js
node_js:
- '8'
install:
- yarn install
script:
- yarn run build
notifications:
  email:
    recipients:
    - shangyunliang@xiaomi.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_d4b70a09816a_key -iv $encrypted_d4b70a09816a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.107.102.216\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- tar -cvjpf dist.tar.bz2 ./dist
- scp dist.tar.bz2 root@39.107.102.216:/var/www
- ssh root@39.107.102.216
  'cd /var/www
  && nginx -s stop
  && rm -rf dist
  && tar -xjvf dist.tar.bz2
  && nginx
  && rm -rf dist.tar.bz2'
addons:
  ssh_known_hosts: 39.107.102.216
