language: node_js
node_js:
  - "8"
install:
  - "yarn install"
script:
  - "yarn run build"
notifications:
  email:
    recipients:
      - shangyunliang@xiaomi.com
    on_success: never # default: change
    on_failure: always # default: always
